vote/urls.py
from django.urls import path

from . import views


app_name = 'vote'
urlpatterns = [
    path('index/', views.active, name='active'),
    path('completed/', views.completed, name='completed'),
    path('send/', views.SendView.as_view(), name='send'),
    path('plot/<int:vote_id>/', views.plot_pic, name='plot_pic'),
    path('<int:vote_id>/', views.detail, name='detail'),
    path('<int:vote_id>/vote/', views.vote, name='vote'),
]

voting/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('vote.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/models.py
from django.db import models
import datetime


class Character(models.Model):
    last_name = models.CharField('Фамилия', max_length=30)
    first_name = models.CharField('Имя', max_length=15)
    middle_name = models.CharField('Отчество', max_length=15)
    photo = models.ImageField('Фото', upload_to='upload')
    date_of_birth = models.DateField('Дата рождения')
    short_biography = models.TextField('Краткая биография')
    vote_count = models.IntegerField('Количество голосов', default=0)

    def age(self):   # определение возраста персонажа по дате рождения
        today = datetime.date.today()
        age = today.year - self.date_of_birth.year
        if today.month < self.date_of_birth.month | \
                (today.month == self.date_of_birth.month & today.day < self.date_of_birth.day):
            age -= 1
        return age

    class Meta:
        ordering = ['-vote_count']
        verbose_name = u'Персонаж'
        verbose_name_plural = u'Персонажи'

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)


class Vote(models.Model):
    name = models.CharField('Название', max_length=200)
    date_start = models.DateField('Дата начала')
    date_end = models.DateField('Дата окончания')
    max_count_vote = models.IntegerField('Максимальное количество голосов', blank=True, null=True)
    character = models.ManyToManyField(Character, verbose_name='Персонаж', blank=True, null=True)

    class Meta:
        verbose_name = u'Голосование'
        verbose_name_plural = u'Голосования'

    def __str__(self):
        return self.name

vote/views.py
import datetime
import io
import xlwt
from io import BytesIO
import matplotlib.pyplot as plt
from apscheduler.schedulers.background import BackgroundScheduler
from django.core.mail import EmailMessage
from django.http import Http404
from django.shortcuts import render, HttpResponse, get_object_or_404, HttpResponseRedirect, redirect
from django.urls import reverse
from django.views.generic import View
from .models import Vote
from threading import Lock

lock = Lock()   # для обхода race condition


# Create your views here.

def get_active_votes():   # нахождение всех активных голосований
    votes_date_filter = Vote.objects.filter(date_start__lt=datetime.date.today(), date_end__gte=datetime.date.today())
    active_votes = []
    for vote in votes_date_filter:
        if vote.max_count_vote:
            if not vote.character.filter(vote_count__gte=vote.max_count_vote).exists():
                active_votes.append(vote)
        else:
            active_votes.append(vote)
    return active_votes


def active(request):
    return render(request, 'vote/active.html', {'votes_active': get_active_votes()})


def completed(request):
    votes_completed = set(Vote.objects.all()).difference(get_active_votes())
    return render(request, 'vote/completed.html', {'votes_completed': votes_completed})


def detail(request, vote_id):
    try:
        vote = Vote.objects.get(pk=vote_id)
        voting_button = True if vote in get_active_votes() else False   # показать/скрыть кнопку для голосования
        time_left = (vote.date_end - datetime.date.today()).days if vote.date_end > datetime.date.today() else 0
    except Vote.DoesNotExist:
        raise Http404("Vote does not exist")
    return render(request, 'vote/detail.html', {'vote': vote, 'voting_button': voting_button, 'time_left': time_left})


def plot_pic(request, vote_id):  # создание графика для голосования
    fig, ax = plt.subplots()
    plt.get_current_fig_manager()
    fig.suptitle('Количество голосов для каждого персонажа')
    ax.set_xlabel("Персонаж")
    ax.set_ylabel("Голоса")

    vote = Vote.objects.get(pk=vote_id)
    data = []
    for character in vote.character.all():
        data.append([character.last_name, character.vote_count])

    size = [x[1] for x in data]
    nums = [x + 1 for x in range(len(size))]
    tick_label = [x[0] for x in data]

    ax.bar(nums, size, tick_label=tick_label, width=0.5, color="#a500ff")
    ax.set_facecolor('seashell')
    fig.set_facecolor('floralwhite')
    fig.set_figwidth(12)
    fig.set_figheight(6)

    buf = io.BytesIO()
    plt.savefig(buf, format="png")
    plt.draw()
    plt.clf()
    response = HttpResponse(buf.getvalue(), content_type="image/jpeg")
    return response


def vote(request, vote_id):
    vote = get_object_or_404(Vote, pk=vote_id)
    try:
        selected_character = vote.character.get(pk=request.POST['character'])
    except (KeyError, Vote.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'vote': vote,
            'error_message': "You didn't select a character.",
        })
    else:
        lock.acquire()
        selected_character.vote_count += 1
        selected_character.save()
        lock.release()
        return HttpResponseRedirect(reverse('vote:detail', args=(vote.id,)))


scheduler = BackgroundScheduler({'apscheduler.timezone': 'Europe/London'})  # планировщик для отправки сообщения


@scheduler.scheduled_job("interval", seconds=60, id="SendView")
class SendView(View):

    def get(self, request):
        votes = Vote.objects.all()
        f = BytesIO()
        book = xlwt.Workbook()
        sheet = book.add_sheet("Результаты голосования")
        count = 0
        for i, vote in enumerate(votes):
            i += count
            sheet.write(0, i, vote.name)
            for k, character in enumerate(vote.character.all()):
                sheet.write(k + 1, i, character.last_name)
                sheet.write(k + 1, i + 1, character.last_name)
                sheet.write(k + 1, i + 2, character.vote_count)
            count += 3
        book.save(f)
        message = EmailMessage(subject="Результаты голосований", body="Выгрузка в xlsx",
                               from_email="random@gmail.com",
                               to=(request.user.email,))
        message.attach('filename.xlsx', f.getvalue(),
                       "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
        message.send()
        return redirect('/admin/')


scheduler.start()

vote/templates/vote/active.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Активные голосования</h1>
    <a href="/completed/">Завершенные голосования</a>
    {% for vote in votes_active %}
        <h3><a href="/{{ vote.id }}">{{ vote.name }}</a></h3> <br>
        {{ vote.date_start }} - {{ vote.date_end }} <br>
        Максимальное количество голосов: {{ vote.max_count_vote }} <br>
        Персонажи:
        <ul>
            {% for character in vote.character.all %}
            <li>
                <img src="{{ character.photo.url }}" width="200px" height="auto"><br>
                {{ character.last_name }} {{ character.first_name }} {{ character.middle_name }}<br>
                Возраст: {{ character.age }}<br>
                Биография: {{ character.short_biography }}<br>
                Голосов: {{ character.vote_count }}
            </li>
            {% endfor %}
        </ul>
        <hr>
    {% endfor %}
</body>
</html>

vote/templates/vote/completed.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Завершенные голосования</h1>
    <a href="/index/">Активные голосования</a>
    {% for vote in votes_completed %}
        <h3><a href="/{{ vote.id }}">{{ vote.name }}</a></h3> <br>

        {{ vote.date_start }} - {{ vote.date_end }} <br>
        Максимальное количество голосов: {{ vote.max_count_vote }} <br>
        Персонажи:
        <ul>
            {% for character in vote.character.all %}
            <li>
                <img src="{{ character.photo.url }}" width="200px" height="auto"> <br>
                {{character.last_name}} {{character.first_name}} {{character.middle_name}} <br>
                Возраст: {{ character.age }} <br>
                Биография: {{ character.short_biography }}<br>
                Голосов: {{ character.vote_count }}
            </li>
            {% endfor %}
        </ul>
        <hr/>
    {% endfor %}
</body>
</html>

vote/templates/vote/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{% url 'vote:vote' vote.id %}" method="post">
        {% csrf_token %}
        <h1>{{ vote.name }}</h1>
        <a href="/index/">К активным</a> | <a href="/completed/">К завершенным</a> <br>
        Осталось дней: {{ time_left }} <br>
        <h3>Персонажи:</h3>
        {% for character in vote.character.all %}
        <input type="radio" name="character" id="character{{ forloop.counter }}" value="{{ character.id }}">
        <label for="character{{ forloop.counter }}">
            <img src="{{ character.photo.url }}" width="200px" height="auto"> <br>
            {{ character.last_name }} {{ character.first_name }} {{ character.middle_name }}<br>
            Возраст: {{ character.age }}<br>
            Краткая биография: {{ character.short_biography }} <br>
            Голосов: {{ character.vote_count }}<br>
        </label> <br>
        {% endfor %}
        {% if voting_button %}
            <input type="submit" value="Голосовать">
        {% endif %}
    </form>
    <img src="/plot/{{vote.id}}" width="640" height="auto">
</body>
</html>